### ISSUE TITLE
Only dahs instead of spinner

### ISSUE THREAD

**Issue by EH-SrdjanDjakovic** [usmanyunusov/nanospinner#21]
When i start the spinner i see only dash:

![Capture](https://user-images.githubusercontent.com/81744565/197079402-d90c1aea-47cb-4ab4-9911-a5c013cde2df.PNG)

This is the code i used for spinner:
`      const spinner = createSpinner("Installing dependencies...");`
`spinner.start();
`

**Comment by usmanyunusov** [comment]
What platform and what terminal do you have?

**Comment by usmanyunusov** [comment]
@EH-SrdjanDjakovic

**Comment by EH-SrdjanDjakovic** [comment]
Window. I realized that windows doesn't have proper Unicode support.
