### ISSUE TITLE
Not restore cursor when the program exits abnormally

### ISSUE THREAD

**Issue by kricsleo** [usmanyunusov/nanospinner#24]
When exiting in the loading state (e.g. `ctrl` + `c`), the cursor is still hidden. 

Do you think it's better to listen to `SIGINT` to restore the cursor when exit?

(Willing to contribute a PR for this. Also if there is anything inappropriate please point it out directly :)

**Comment by 43081j** [comment]
@kricsleo any chance you can submit a PR for this?

maybe @usmanyunusov can help us get it merged

we can just listen for `SIGINT` and `SIGTERM`, and call `stop` when they fire

**Comment by kricsleo** [comment]
@43081j Sure ❤️

**Comment by usmanyunusov** [comment]
The fix was released in 1.2.0.
