### ISSUE TITLE
Difference vs ora - double printing on exit

### ISSUE THREAD

**Issue by JamesHenry** [usmanyunusov/nanospinner#32]
Thanks for the great work to help make the ecosystem more efficient!

I would like to replace our usage of ora with nanospinner in https://github.com/nrwl/nx - our overall tracking issue is here: https://github.com/es-tooling/ecosystem-cleanup/issues/117

I went through our usage and fortunately we don't require the multiple spinners support. Things are nearly ready to go but I found one blocking bug, here is a repro:

https://stackblitz.com/edit/stackblitz-starters-dmnx9n?file=package.json&view=editor

- Run `node ora.js`
- Run `node nanospinner.js`

You will see that ora does not print again after the error message is printed as expected, but nanospinner does.

![image](https://github.com/user-attachments/assets/4bd098a5-0568-4d7c-8288-068c8f28fac3)

![image](https://github.com/user-attachments/assets/1625a2b3-3cb6-4ac4-809a-f348f7f5cf4b)

**Comment by usmanyunusov** [comment]
@JamesHenry I'll take a look soon

**Comment by usmanyunusov** [comment]
@JamesHenry fix relese 1.2.2

**Comment by JamesHenry** [comment]
Ah cool thank you @usmanyunusov, I also wanted to make you aware of the discussion happening here: https://github.com/tinylibs/picospinner/pull/5
