### ISSUE TITLE
start() should have opts similar to stop()

### ISSUE THREAD

**Issue by redaxmedia** [usmanyunusov/nanospinner#9]
There should be the option to pass a text on `start()` like ora does.

Otherwise I have to do this:

```
spinner.start();
spinner.update({
    text: 'start the spinner'
});
```

**Comment by usmanyunusov** [comment]
Released in 0.2.2

**Comment by redaxmedia** [comment]
Great, should be a 0.3.0 cause this is an api non-breaking change... patch releases for fixes only

**Comment by usmanyunusov** [comment]
I'll take for the future!
